research_task:
  description: >
    Description: Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
    Expected Output: A list with 10 bullet points of the most relevant information about {topic}
    User Input: Don't ask user for any inputs. Use the best of your context, to complete the task end to end. 

notion_task:
  description: >
    Description: Write a page on notion that summarizes {topic} research activity under "research" page, adding all the research on {topic} so far.
    Expected Output: A Notion page with a good title filled with all the research. 
    User Input: Don't ask user for any inputs. Use the best of your context, to complete the task end to end. 

slack_task:
  description: >
    Description: Write a message on slack channel 'ram' that summarizes complete {topic} research activity. Write a summary of your findings and attach the report.
    Expected Output: A slack message with a summary of entire actions done and final output.  
    User Input: Don't ask user for any inputs. Use the best of your context, to complete the task end to end. 
